-- upgrade --
CREATE TABLE IF NOT EXISTS "admin" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "username" VARCHAR(50) NOT NULL UNIQUE,
    "password" VARCHAR(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS "user" (
    "id" CHAR(36) NOT NULL  PRIMARY KEY,
    "username" VARCHAR(30) NOT NULL UNIQUE,
    "email" VARCHAR(50) NOT NULL UNIQUE,
    "nickname" VARCHAR(30) NOT NULL,
    "hashed_password" VARCHAR(200) NOT NULL,
    "is_verified" INT NOT NULL  DEFAULT 0,
    "is_active" INT NOT NULL  DEFAULT 0,
    "registered_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "todo" (
    "id" CHAR(36) NOT NULL  PRIMARY KEY,
    "title" VARCHAR(200) NOT NULL,
    "due_date" DATE NOT NULL,
    "is_done" INT NOT NULL  DEFAULT 0,
    "creator_id" CHAR(36) NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
